spring.application.name=Pearl Spring Project
server.port = 8081

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/pys_nov25_sp
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

